### ISSUE TITLE
Fix or Remove broken and obsolete functionality

### ISSUE THREAD

**Issue by schweikl** [VoglSebastian/evosuite#33]
As part of the current refactoring, we're also in the process of cleaning up EvoSuite by fixing (e.g., Local Search) or removing broken and rarely-used functionality. Below we maintain a list of things that should be fixed or removed:
- [x] ~LS~ (Issue #16, fixed by PR #18)
- [x] `evosuite-generated` tests (fixed by PR #48)
- [x] ~regression test generation~ (Issue #14, removed by PR #28)
- [x] JEE support (e.g., Spring) (removed by PR #46)

DSE can remain (for now) but may be removed in the future.
